In [4]:
import numpy as np 
a= np.array([1,2,3,5])
x=a.tolist()
print(a)
print(x)

[1 2 3 5]
[1, 2, 3, 5]


In [6]:
import numpy as np
x=np.array([[6]], dtype=np.float64)
y=np.array([[4]], dtype=np.float64)
z=np.array([[2]], dtype=np.float64)
A=np.add(x, y, z)
print(x)
print(y)
print(z)

[[6.]]
[[4.]]
[[10.]]


In [2]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print(" 10 =", x[x>10])
print( np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
 10 = [20 20 30 40]
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [17]:
import nu.mpy as np
input: A[]{4, 1, 2, 1, 1, 2} , B[]= ({4, 1, 2, 1, 1, 2})
        C = np.array[] =({5, 9, 5, 1, 2, 3}) 
        print("array:")
        print(C)
        print(A=B)
        add C to A and B

SyntaxError: invalid syntax (<ipython-input-17-5e0ec605e72d>, line 2)

In [18]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.23619374 0.12653621 0.03869197 0.90368401 0.70564361 0.77417831
  0.64261897 0.2029923  0.36775604 0.30393688]
 [0.86760504 0.73116692 0.07213351 0.1963393  0.93431795 0.85601987
  0.01607526 0.24535299 0.10093507 0.46874607]
 [0.79345966 0.32729243 0.35974289 0.48341105 0.00278428 0.57790458
  0.65874012 0.3085398  0.01345704 0.36973301]
 [0.54668204 0.0748319  0.45725059 0.80739821 0.55269322 0.3386472
  0.42578177 0.64703038 0.62360731 0.87111123]
 [0.23133476 0.10857535 0.65929947 0.39780139 0.68237156 0.60757834
  0.60087868 0.3356318  0.12799019 0.47041935]]

Subtract the mean of each row of the said matrix:

[[-0.19402946 -0.30368699 -0.39153123  0.47346081  0.27542041  0.3439551
   0.21239576 -0.2272309  -0.06246716 -0.12628632]
 [ 0.41873584  0.28229773 -0.37673569 -0.2525299   0.48544875  0.40715067
  -0.43279394 -0.20351621 -0.34793413  0.01987687]
 [ 0.40395317 -0.06221405 -0.02976359  0.09390457 -0.38672221  0.1883981
   0.26923363 -0.08096669 -0.3760